services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    env_file:
      - ../../.env  # Global env file
      - .env     # Service-specific env file
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${WG_HOST_IP}

      # Optional:
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      - PORT=${WG_WEBUI_PORT}
      - WG_PORT=${WG_VPN_PORT}
      # - WG_CONFIG_PORT=92820
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=$$2a$$12$$vkvKpeEAHD78gasyawIod.1leBMKg8sBwKW.pQyNsq78bXV3INf2G # (needs double $$, hash of 'prometheus_password'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - ${WG_VPN_PORT}:51820/udp
      - ${WG_WEBUI_PORT}:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.rule=Host(`${WG_SUBDOMAIN}.${DEFAULT_DOMAIN}`)
      - traefik.http.routers.wireguard.entrypoints=https
      - traefik.http.routers.wireguard.tls=true
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
      - homepage.name=${HOMEPAGE_WG_NAME}
      - homepage.description=${HOMEPAGE_WG_DESCRIPTION}
      - homepage.group=${HOMEPAGE_WG_GROUP}
      - homepage.href=https://${WG_SUBDOMAIN}.${DEFAULT_DOMAIN}
      - homepage.icon=${HOMEPAGE_WG_ICON}
      - homepage.weight=${HOMEPAGE_WG_WEIGHT}
      - homepage.widget.type=${HOMEPAGE_WG_WIDGET_TYPE}
      - homepage.widget.url=https://${WG_SUBDOMAIN}.${DEFAULT_DOMAIN}
      - homepage.widget.password=${HOMEPAGE_WG_WIDGET_PASSWORD}
    networks:
      - proxy

networks:
  proxy:
    external: true 