include:
  - traefik/docker-compose.yml
  - services/keycloak/docker-compose.yml
  - services/portainer/docker-compose.yml
  - services/watchtower/docker-compose.yml
  - services/homepage/docker-compose.yml
  - services/wireguard/docker-compose.yml
  - services/redis/docker-compose.yml
  - services/postgres/docker-compose.yml
  - services/freefilesync/docker-compose.yml
  - services/uptime-kuma/docker-compose.yml
  - services/n8n/docker-compose.yml
  - services/navidrome/docker-compose.yml
  - services/audiobookshelf/docker-compose.yml
  

#services:

# volumes:
#   keycloak_pg_data:
#     driver: local

secrets:
  cf_api_token:
    file: ./traefik/cf_api_token.txt

networks:
  proxy:
    external: true
