include:
  - traefik/docker-compose.yml
  # - services/watchtower/docker-compose.yml
  # - services/wireguard/docker-compose.yml
  # - services/postgres/docker-compose.yml
  # - services/flyway/docker-compose.yml
  # - services/pgbackups/docker-compose.yml
  # - services/pgadmin/docker-compose.yml
  # - services/redis/docker-compose.yml
  # - services/freefilesync/docker-compose.yml
  # - services/homepage/docker-compose.yml

#services:

# volumes:
#   postgres_data:
#   redis_data:

secrets:
  cf_api_token:
    file: ./traefik/cf_api_token.txt

networks:
  proxy:
    external: true
