services:

  watchtower:
    image: containrrr/watchtower
    container_name: ${WATCHTOWER_CONTAINERNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    ports:
      - ${WATCHTOWER_PORT}:8080
    restart: unless-stopped
    env_file:
      - ../../.env  # Global env file
      - .env     # Service-specific env file
    environment:
      WATCHTOWER_DISABLE_CONTAINERS: "${WATCHTOWER_DISABLE_CONTAINERS}"
      WATCHTOWER_SCHEDULE: "0 0 1 * * *"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "${WATCHTOWER_EMAILFROM}"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "${WATCHTOWER_EMAILTO}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "${WATCHTOWER_EMAILSERVER}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "${WATCHTOWER_EMAILUSER}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "${WATCHTOWER_EMAILPASSWORD}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "${WATCHTOWER_EMAILPORT}"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "${WATCHTOWER_NOTIFICAITONS_HOSTNAME}"
      TZ: "${TIMEZONE}"
      WATCHTOWER_NO_STARTUP_MESSAGE: true
      WATCHTOWER_HTTP_API_TOKEN: "${WATCHTOWER_API_TOKEN}"
      WATCHTOWER_HTTP_API_UPDATE: true
      WATCHTOWER_HTTP_API_METRICS: true
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: true
      WATCHTOWER_TIMEOUT: 30s
    labels:
      - homepage.name=${HOMEPAGE_WATCHTOWER_NAME}
      - homepage.description=${HOMEPAGE_WATCHTOWER_DESCRIPTION}
      - homepage.group=${HOMEPAGE_WATCHTOWER_GROUP}
      - homepage.href=http://${WATCHTOWER_IP}:${WATCHTOWER_PORT}
      - homepage.icon=${HOMEPAGE_WATCHTOWER_ICON}
      - homepage.weight=${HOMEPAGE_WATCHTOWER_WEIGHT}
      - homepage.widget.type=${HOMEPAGE_WATCHTOWER_WIDGET_TYPE}
      - homepage.widget.url=http://${WATCHTOWER_IP}:${WATCHTOWER_PORT}
      - homepage.widget.key=${WATCHTOWER_API_TOKEN}